version: '3'

services:
  grafana:
    image: grafana/grafana:9.2.6
    user: 1000:1000
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana/conf:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

  prometheus:
    image: prom/prometheus:v2.40.2
    user: 1000:1000
    depends_on:
      - node_exporter
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/conf:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml']

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  blackbox:
     image: prom/blackbox-exporter:v0.22.0
     privileged: true
     volumes: 
       - ./blackbox/:/config
     ports: 
       - 9115
     command: ['--config.file=/config/blackbox.yml']

  node_exporter:
    image: prom/node-exporter:v1.4.0
    restart: unless-stopped
    expose:
      - 9100
    extra_hosts:
      - "tranmission:192.168.1.2"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  mikrotik_exporter:
    image: andreiker/mikrotik-exporter-arm64:1.0.12-DEVEL
    restart: unless-stopped
    expose:
      - 9436
    volumes:
      - ./mikrotik/conf:/app/conf/

  transmission_exporter:
    image: andreiker/transmission-exporter-arm64:latest
    restart: unless-stopped
    expose:
      - 19091
    environment:
      - TRANSMISSION_ADDR=${TRANSMISSION_ADDR}
      - TRANSMISSION_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
      - WEB_ADDR=${WEB_ADDR}
      - WEB_PATH=${WEB_PATH}

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.46.0 
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --global_housekeeping_interval=30s
      - --housekeeping_interval=5s
      - --storage_duration=1m0s
